import ckit

lredit_appname = "LREdit"
lredit_dirname = "LREdit"
lredit_version = "1.76"

_startup_string_fmt = """\
%s version %s:
  http://sites.google.com/site/craftware/
"""

def startupString():
    return _startup_string_fmt % ( lredit_appname, lredit_version )


strings_ja = {
    "common_yes"        : "はい",
    "common_no"         : "いいえ",
    "common_done"       : "完了.",
    "common_aborted"    : "中断しました.",
    "common_failed"     : "失敗.",
    
    "menu_file"             : "ファイル(&F)",
    "menu_new"              : "新規作成(&N)",
    "menu_open"             : "開く(&O)",
    "menu_reopen"           : "開き直す(&R)",
    "menu_close"            : "閉じる(&C)",
    "menu_project"          : "プロジェクト(&P)",
    "menu_open_project"     : "開く(&O)",
    "menu_close_project"    : "閉じる(&C)",
    "menu_edit_project"     : "編集(&E)",
    "menu_project_file_list": "プロジェクトファイル一覧(&F)",
    "menu_save"             : "保存(&S)",
    "menu_save_as"          : "名前を付けて保存(&A)",
    "menu_save_all"         : "すべて保存(&L)",
    "menu_encoding"         : "エンコーディング(&E)",
    "menu_recent_files"     : "最近のファイル(&I)",
    "menu_recent_projects"  : "最近のプロジェクト(&J)",
    "menu_quit"             : "終了(&Q)",

    "menu_edit"         : "編集(&E)",
    "menu_undo"         : "元に戻す(&U)",
    "menu_redo"         : "やり直し(&R)",
    "menu_cut"          : "切り取り(&T)",
    "menu_copy"         : "コピー(&C)",
    "menu_paste"        : "貼り付け(&P)",
    "menu_delete"       : "削除(&D)",
    "menu_select_all"   : "すべてを選択(&L)",
    "menu_convert_char" : "文字変換(&V)",
    "menu_to_upper"     : "大文字化(&U)",
    "menu_to_lower"     : "小文字化(&L)",
    "menu_to_zenkaku"   : "全角に変換(&Z)",
    "menu_to_hankaku"   : "半角に変換(&H)",
    "menu_complete"     : "単語補完(&W)",
    "menu_jump_lineno"  : "指定行ジャンプ(&G)",

    "menu_search"       : "検索(&S)",
    "menu_search_next"  : "次を検索(&N)",
    "menu_search_prev"  : "前を検索(&P)",
    "menu_grep"         : "ファイルから検索(&G)",
    "menu_tags"         : "シンボル検索(&Y)",
    "menu_tags_jump"    : "定義位置へジャンプ(&J)",
    "menu_tags_back"    : "ジャンプ元へ戻る(&B)",
    "menu_load_tags"    : "TAGSの読み込み(&L)",
    "menu_generate_tags": "TAGSの生成(&G)",
    "menu_replace"      : "置換(&R)",
    "menu_compare"      : "比較(&C)",

    "menu_view"             : "表示(&V)",
    "menu_another_pane"     : "他方のペイン(&A)",
    "menu_doclist"          : "文書選択(&D)",

    "menu_tool"             : "ツール(&T)",
    "menu_bookmark_list"    : "ブックマーク一覧(&B)",
    "menu_bookmark1"        : "ブックマーク1(&1)",
    "menu_bookmark2"        : "ブックマーク2(&2)",
    "menu_bookmark3"        : "ブックマーク3(&3)",
    "menu_bookmark_next"    : "次のブックマークへ(&N)",
    "menu_bookmark_prev"    : "前のブックマークへ(&P)",
    "menu_outline"          : "アウトライン(&O)",
    "menu_expand_tab"       : "タブをスペースに展開(&T)",
    "menu_remove_trailing_space" : "行末の空白を削除(&S)",
    "menu_remove_empty_lines" : "空行を削除(&E)",
    "menu_remove_marked_lines" : "ブックマークされている行を削除(&M)",
    "menu_remove_unmarked_lines" : "ブックマークされていない行を削除(&U)",
    "menu_config_menu"      : "設定(&C)",
    "menu_config_edit"      : "config.pyの編集(&E)",
    "menu_config_reload"    : "config.pyの再読み込み(&R)",

    "menu_help"             : "ヘルプ(&H)",
    "menu_about"            : "バージョン情報(&A)",
    
    "config_menu"                   : "設定メニュー",
    "display_option"                : "表示オプション",
    "operation_option"              : "操作オプション",
    "misc_option"                   : "その他のオプション",
    "theme"                         : "テーマ",
    "font"                          : "フォント",
    "font_size"                     : "フォントサイズ",
    "visible"                       : "表示",
    "invisible"                     : "非表示",
    "menubar"                       : "メニューバー",
    "menubar_visibility"            : "メニューバーの表示",
    "wallpaper"                     : "壁紙",
    "wallpaper_visibility"          : "壁紙の表示",
    "wallpaper_strength"            : "壁紙の濃さ",
    "application_name"              : "アプリケーション名",
    "locale"                        : "表示言語",
    "locale_en_US"                  : "英語",
    "locale_ja_JP"                  : "日本語",
    "isearch_type"                  : "インクリメンタルサーチ動作",
    "isearch_type_strict"           : "厳密     : ABC*",
    "isearch_type_partial"          : "部分一致 : *ABC*",
    "isearch_type_inaccurate"       : "あいまい : *A*B*C*",
    "isearch_type_migemo"           : "Migemo   : *AIUEO*",
    "beep_type"                     : "ビープ音",
    "beep_type_disabled"            : "無効",
    "beep_type_enabled"             : "有効",
    "directory_separator"           : "ディレクトリ区切り文字",
    "directory_separator_slash"     : "スラッシュ       : / ",
    "directory_separator_backslash" : "バックスラッシュ : \\ ",
    "drive_case"                    : "ドライブ文字の大文字/小文字",
    "drive_case_nocare"             : "気にしない",
    "drive_case_upper"              : "大文字",
    "drive_case_lower"              : "小文字",
    "edit_config"                   : "config.py を編集",
    "reload_config"                 : "config.py を再読み込み",
    
    "msgbox_title_generic_error"    : "エラー",
    "msgbox_title_insert_task"      : "タスクの処理順序の確認",
    "msgbox_ask_insert_task"        : "優先的に処理を行いますか？",
    "msgbox_title_save"             : "保存確認",
    "msgbox_ask_save_document"      : "[%s] を保存しますか？",
    "msgbox_title_modified_reload"  : "再読み込み確認",
    "msgbox_ask_modified_reload"    : "%sが外部で変更されています。再読み込みしますか？",
    "msgbox_title_wallpaper_error"  : "壁紙のエラー",
    "msgbox_wallpaper_filename_empty" : "Wallpaperコマンドを使って、壁紙ファイルを指定してください。",
    "msgbox_title_modified_reopen"  : "変更内容破棄の確認",
    "msgbox_ask_modified_reopen"    : "%sは変更されていますが、開きなおしますか？",
    "msgbox_title_new_window"       : "新規 LREdit ウインドウの確認",
    "msgbox_ask_new_window"         : "新しいウインドウを開きますか？",
    
    "statusbar_task_reserved"       : "タスクを予約しました : %s",
    "statusbar_open_failed"         : "オープン失敗 : %s",
    "statusbar_switch_doc_failed"   : "ドキュメント切り替え失敗 : %s",
    "statusbar_regex_wrong"         : "正規表現 [%s] に誤りがあります.",
    "statusbar_aborted"             : "タスクを中断しました.",
    "statusbar_grep_finished"       : "Grep : %d 件ヒットしました.",
    "statusbar_replace_finished"    : "Replace : %d 箇所置換しました.",
    "statusbar_not_saved"           : "ファイルが保存されていません.",
    "statusbar_jump_failed"         : "ジャンプできません.",
    "statusbar_symbol_not_found"    : "シンボル [%s] の定義位置が見つかりません.",
    "statusbar_tags_generating"     : "Tags ファイルを生成中.",
    "statusbar_tags_generated"      : "Tags ファイルを生成しました.",
    "statusbar_tags_loading"        : "Tags ロード中.",
    "statusbar_tags_loaded"         : "Tags ファイルをロードしました.",
    "statusbar_project_opened"      : "プロジェクトファイルをオープンしました : %s",
    "statusbar_project_closed"      : "プロジェクトファイルをクローズしました.",
    
    "not_textfile"                          : "テキストファイルではありません.",
    "saving"                                : "保存中...",
    "memory_statistics"                     : "メモリ統計情報",
    "config_reloaded"                       : "設定スクリプトをリロードしました.",
    "project_reloaded"                      : "プロジェクトファイルをリロードしました.",
    "help_opening"                          : "Helpを起動",
    "project_not_opened"                    : "プロジェクトファイルがオープンされていません.",
    "mode_not_found"                        : "モード [%s] が見つかりません.",
    "mode_enabled"                          : "モード [%s] を有効にしました.",
    "mode_disabled"                         : "モード [%s] を無効にしました.",
    
    "error_prefix"                  : "ERROR : ",
    "error_already_exists"          : "ERROR : すでに存在しています.",
    "error_ini_file_load_failed"    : "ERROR : INIファイルの読み込み中にエラーが発生しました.",
    "error_connection_failed"       : "ERROR : 接続失敗 : %s",
    "error_open_failed"             : "ERROR : オープン失敗 : %s",
    "error_load_failed"             : "ERROR : ロード失敗 : %s",
    "error_out_of_memory"           : "ERROR : メモリ不足 : %s",
    "error_invalid_wallpaper"       : "ERROR : 壁紙ファイルとして使用できない : %s",
    "error_unknown_parameter"       : "ERROR : 不明なパラメタ : %s",
    "error_unknown_encoding"        : "ERROR : 不明なエンコーディング名 : %s",
    "error_unknown_lineend"         : "ERROR : 不明な改行コード : %s",
}

strings_en = {
    "common_yes"        : "Yes",
    "common_no"         : "No",
    "common_done"       : "Done.",
    "common_aborted"    : "Aborted.",
    "common_failed"     : "Failed.",

    "menu_file"             : "&File",
    "menu_new"              : "&New",
    "menu_open"             : "&Open",
    "menu_reopen"           : "&Reopen",
    "menu_close"            : "&Close",
    "menu_project"          : "&Project",
    "menu_open_project"     : "&Open",
    "menu_close_project"    : "&Close",
    "menu_edit_project"     : "&Edit",
    "menu_project_file_list": "Project &File List",
    "menu_save"             : "&Save",
    "menu_save_as"          : "Save &As",
    "menu_save_all"         : "Save A&ll",
    "menu_encoding"         : "&Encoding",
    "menu_recent_files"     : "Recent F&iles",
    "menu_recent_projects"  : "Recent Pro&jects",
    "menu_quit"             : "&Quit",

    "menu_edit"         : "&Edit",
    "menu_undo"         : "&Undo",
    "menu_redo"         : "&Redo",
    "menu_cut"          : "Cu&t",
    "menu_copy"         : "&Copy",
    "menu_paste"        : "&Paste",
    "menu_delete"       : "&Delete",
    "menu_select_all"   : "Select A&ll",
    "menu_convert_char" : "Con&vert",
    "menu_to_upper"     : "&Uppercase",
    "menu_to_lower"     : "&Lowercase",
    "menu_to_zenkaku"   : "&Zenkaku",
    "menu_to_hankaku"   : "&Hankaku",
    "menu_complete"     : "&Word Completion",
    "menu_jump_lineno"  : "&Goto Line",

    "menu_search"       : "&Search",
    "menu_search_next"  : "Search &Next",
    "menu_search_prev"  : "Search &Prev",
    "menu_grep"         : "&Grep",
    "menu_tags"         : "S&ymbol Search",
    "menu_tags_jump"    : "&Jump to Definition",
    "menu_tags_back"    : "&Back to Original Position",
    "menu_load_tags"    : "&Load TAGS",
    "menu_generate_tags": "&Generate TAGS",
    "menu_replace"      : "&Replace",
    "menu_compare"      : "&Compare",

    "menu_view"         : "&View",
    "menu_another_pane" : "&Another Pane",
    "menu_doclist"      : "&Document List",

    "menu_tool"             : "&Tool",
    "menu_bookmark_list"    : "&Bookmark List",
    "menu_bookmark1"        : "Bookmark&1",
    "menu_bookmark2"        : "Bookmark&2",
    "menu_bookmark3"        : "Bookmark&3",
    "menu_bookmark_next"    : "&Next Bookmark",
    "menu_bookmark_prev"    : "&Prev Bookmark",
    "menu_outline"          : "&Outline",
    "menu_expand_tab"       : "Expand &Tab",
    "menu_remove_trailing_space" : "Remove Trailing &Space",
    "menu_remove_empty_lines" : "Remove &Empty Lines",
    "menu_remove_marked_lines" : "Remove &Marked Lines",
    "menu_remove_unmarked_lines" : "Remove &Unmarked Lines",
    "menu_config_menu"      : "&Config",
    "menu_config_edit"      : "&Edit config.py",
    "menu_config_reload"    : "&Reload config.py",

    "menu_help"             : "&Help",
    "menu_about"            : "&About",

    "config_menu"                   : "Configuration Menu",
    "display_option"                : "Display Options",
    "operation_option"              : "Operation Options",
    "misc_option"                   : "Misc Options",
    "theme"                         : "Theme",
    "font"                          : "Font",
    "font_size"                     : "Font Size",
    "visible"                       : "Visible",
    "invisible"                     : "Invisible",
    "menubar"                       : "Menu Bar",
    "menubar_visibility"            : "Menu Bar Visibility",
    "wallpaper"                     : "Wallpaper",
    "wallpaper_visibility"          : "Wallpaper Visibility",
    "wallpaper_strength"            : "Wallpaper Strength",
    "application_name"              : "Application Name",
    "locale"                        : "Display Language",
    "locale_en_US"                  : "English",
    "locale_ja_JP"                  : "Japanese",
    "isearch_type"                  : "Incremental Search Behavior",
    "isearch_type_strict"           : "Strict     : ABC*",
    "isearch_type_partial"          : "Partial    : *ABC*",
    "isearch_type_inaccurate"       : "Inaccurate : *A*B*C*",
    "isearch_type_migemo"           : "Migemo     : *AIUEO*",
    "beep_type"                     : "Beep Sound",
    "beep_type_disabled"            : "Diabled",
    "beep_type_enabled"             : "Enabled",
    "directory_separator"           : "Directory Separator",
    "directory_separator_slash"     : "Slash       : / ",
    "directory_separator_backslash" : "BackSlash   : \\ ",
    "drive_case"                    : "Case of Drive Letter",
    "drive_case_nocare"             : "Don't care",
    "drive_case_upper"              : "Upper case",
    "drive_case_lower"              : "Lower case",
    "edit_config"                   : "Edit config.py",
    "reload_config"                 : "Reload config.py",

    "msgbox_title_generic_error"    : "Error",
    "msgbox_title_insert_task"      : "Task Order",
    "msgbox_ask_insert_task"        : "proceed preferentially?",
    "msgbox_title_save"             : "Save",
    "msgbox_ask_save_document"      : "Save [%s] ?",
    "msgbox_title_modified_reload"  : "Reload",
    "msgbox_ask_modified_reload"    : "%s is modified from outside. Reload this file?",
    "msgbox_title_wallpaper_error"  : "Wallpaper",
    "msgbox_wallpaper_filename_empty" : "Using Wallpaper command, specify the filename of wallpaper.",
    "msgbox_title_modified_reopen"  : "Reopen",
    "msgbox_ask_modified_reopen"    : "%s is modified. Is it OK to destroy this modification and reopen this file?",
    "msgbox_title_new_window"       : "New LREdit window",
    "msgbox_ask_new_window"         : "Open a new window?",
    
    "statusbar_task_reserved"       : "Reserved task : %s",
    "statusbar_open_failed"         : "Open failed : %s",
    "statusbar_switch_doc_failed"   : "Wwitching document failed : %s",
    "statusbar_regex_wrong"         : "Regular expression [%s] is wrong.",
    "statusbar_aborted"             : "Aborted Task.",
    "statusbar_grep_finished"       : "Grep : found %d lines.",
    "statusbar_replace_finished"    : "Replace : Replaced %d places.",
    "statusbar_not_saved"           : "Not saved.",
    "statusbar_jump_failed"         : "Jump failed.",
    "statusbar_symbol_not_found"    : "Symbol [%s] is not found.",
    "statusbar_tags_generating"     : "Generating Tags.",
    "statusbar_tags_generated"      : "Generated Tags.",
    "statusbar_tags_loading"        : "Loading Tags.",
    "statusbar_tags_loaded"         : "Loaded Tags.",
    "statusbar_project_opened"      : "Opened project file : %s",
    "statusbar_project_closed"      : "Closed project file.",
    
    "not_textfile"                          : "Not a text file.",
    "saving"                                : "Saving...",
    "memory_statistics"                     : "Memory Statistics",
    "config_reloaded"                       : "Config file reloaded.",
    "project_reloaded"                      : "Project file reloaded.",
    "help_opening"                          : "Opening Help...",
    "project_not_opened"                    : "Project is not opened.",
    "mode_not_found"                        : "Mode [%s] is not found.",
    "mode_enabled"                          : "Mode [%s] is enabled.",
    "mode_disabled"                         : "Mode [%s] is disabled.",

    "error_prefix"                  : "ERROR : ",
    "error_already_exists"          : "ERROR : Already exists.",
    "error_ini_file_load_failed"    : "ERROR : loading INI file failed.",
    "error_connection_failed"       : "ERROR : Connection failed : %s",
    "error_open_failed"             : "ERROR : Open failed : %s",
    "error_load_failed"             : "ERROR : Load failed : %s",
    "error_out_of_memory"           : "ERROR : Out of memory : %s",
    "error_invalid_wallpaper"       : "ERROR : Invalid wallpaper file : %s",
    "error_unknown_parameter"       : "ERROR : Unknown parameter : %s",
    "error_unknown_encoding"        : "ERROR : Unknown encording name : %s",
    "error_unknown_lineend"         : "ERROR : Unknown line end name : %s",
}

ckit.strings_ja.update(strings_ja)
ckit.strings_en.update(strings_en)

def setLocale(locale):
    ckit.setLocale(locale)

